=== Regfreed/stuff/sprakse/labsensors/src/hr/siemens/cvc/labsensors/schema/brokerConfiguration.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration"
	targetNamespace="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration"
	elementFormDefault="qualified" version="1.0">
	<xs:element name="BrokerConfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Protocol" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="protocolSpec">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ServerIp">
											<xs:simpleType>
												<xs:restriction base="xs:string">
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ServerPort">
											<xs:simpleType>
												<xs:restriction base="xs:int">
												<xs:minInclusive value="0" />
													<xs:maxInclusive value="65535" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Username">
											<xs:simpleType>
												<xs:restriction base="xs:string">
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Password">
											<xs:simpleType>
												<xs:restriction base="xs:string">
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Regfreed/stuff/sprakse/labsensors/config/BrokerConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<conf:BrokerConfig
	xmlns:conf="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration ../src/hr/siemens/cvc/labsensors/schema/brokerConfiguration.xsd ">
	<conf:Protocol>
		<conf:Name>MQTT</conf:Name>
		<conf:protocolSpec>
			<conf:ServerIp>conf:ServerIp</conf:ServerIp>
			<conf:ServerPort>0</conf:ServerPort>
			<conf:Username>conf:Username</conf:Username>
			<conf:Password>conf:Password</conf:Password>
		</conf:protocolSpec>
	</conf:Protocol>
	<conf:Protocol>
		<conf:Name>AMQP</conf:Name>
		<conf:protocolSpec>
			<conf:ServerIp>conf:ServerIp</conf:ServerIp>
			<conf:ServerPort>0</conf:ServerPort>
			<conf:Username>conf:Username</conf:Username>
			<conf:Password>conf:Password</conf:Password>
		</conf:protocolSpec>
	</conf:Protocol>
	<conf:Protocol>
		<conf:Name>OPCUA</conf:Name>
		<conf:protocolSpec>
			<conf:ServerIp>conf:ServerIp</conf:ServerIp>
			<conf:ServerPort>0</conf:ServerPort>
			<conf:Username>conf:Username</conf:Username>
			<conf:Password>conf:Password</conf:Password>
		</conf:protocolSpec>
	</conf:Protocol>
</conf:BrokerConfig>
