=== Regfreed/stuff/sprakse/labsensors/src/hr/siemens/cvc/labsensors/schema/SensorsConfiguration.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:conf="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration"
	targetNamespace="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration"
	elementFormDefault="qualified" version="1.0">
	<xs:element name="SensorConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Sensor" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Protocal">
								<xs:simpleType>
									<xs:restriction base="xs:string">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Topic">
								<xs:simpleType>
									<xs:restriction base="xs:string">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="QPS">
								<xs:simpleType>
									<xs:restriction base="xs:int">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="MaxQ">
								<xs:simpleType>
									<xs:restriction base="xs:long">
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="DataElements" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ElementName">
											<xs:simpleType>
												<xs:restriction base="xs:string">
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ElementType">
											<xs:simpleType>
												<xs:restriction base="xs:string">
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="valid">
											<xs:simpleType>
												<xs:restriction base="xs:int">
													<xs:minInclusive value="0" />
													<xs:maxInclusive value="100" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="invalid">
											<xs:simpleType>
												<xs:restriction base="xs:int">
													<xs:minInclusive value="0" />
													<xs:maxInclusive value="100" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Regfreed/stuff/sprakse/labsensors/config/SensorConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<conf:SensorConfiguration xmlns:conf="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration ../src/hr/siemens/cvc/labsensors/schema/SensorsConfiguration.xsd ">
  <conf:Sensor>
    <conf:Name>conf:Name</conf:Name>
    <conf:Protocal>conf:Protocal</conf:Protocal>
    <conf:Topic>conf:Topic</conf:Topic>
    <conf:QPS>0</conf:QPS>
    <conf:MaxQ>0</conf:MaxQ>
    <conf:DataElements>
      <conf:ElementName>conf:ElementName</conf:ElementName>
      <conf:ElementType>conf:ElementType</conf:ElementType>
      <conf:valid>0</conf:valid>
      <conf:invalid>0</conf:invalid>
    </conf:DataElements>
    <conf:DataElements>
      <conf:ElementName>conf:ElementName</conf:ElementName>
      <conf:ElementType>conf:ElementType</conf:ElementType>
      <conf:valid>0</conf:valid>
      <conf:invalid>0</conf:invalid>
    </conf:DataElements>
    <conf:DataElements>
      <conf:ElementName>conf:ElementName</conf:ElementName>
      <conf:ElementType>conf:ElementType</conf:ElementType>
      <conf:valid>0</conf:valid>
      <conf:invalid>0</conf:invalid>
    </conf:DataElements>
  </conf:Sensor>
</conf:SensorConfiguration>
